name: Prepare fastly CLI in CI
description: This action prepare fastly CLI with the specified version.

inputs:
    gh-token:
        required: true

runs:
    using: composite
    steps:
        # https://github.com/fastly/compute-actions
        - name: Set up fastly CLI
          uses: fastly/compute-actions/setup@3b4355cb74cc7428a92dad1194bd564898372d55
          with:
              cli_version: "12.1.0"
              viceroy_version: "0.14.2"
              token: ${{ inputs.gh-token }}
