name: Prepare fastly CLI in CI
description: This action prepare fastly CLI with the specified version.

inputs:
    gh-token:
        required: true

runs:
    using: composite
    steps:
        # https://github.com/fastly/compute-actions
        - name: Set up fastly CLI
          uses: fastly/compute-actions/setup@22ed4d3d07e0d2470afa1a5e896de369b7b23a0f
          with:
              cli_version: "10.13.3"
              viceroy_version: "0.12.1"
              token: ${{ inputs.gh-token }}
