name: Prepare fastly CLI in CI
description: This action prepare fastly CLI with the specified version.

inputs:
    gh-token:
        required: true

runs:
    using: composite
    steps:
        # https://github.com/fastly/compute-actions
        - name: Set up fastly CLI
          uses: fastly/compute-actions/setup@9ca64d641e165464cd4c0c988f2e549dc7d43b49 # v13
          with:
              cli_version: "14.2.0"
              viceroy_version: "0.16.2"
              token: ${{ inputs.gh-token }}
