name: Upload a build artifact
description: This action provides a uniform way to upload a build artifact.

inputs:
    git-sha:
        required: true
    release-channel:
        required: true
    build-type:
        required: tru
    working-directory:
        default: ${{ github.workspace }}
        required: false

runs:
    using: composite
    steps:
        - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
          with:
              name: application-${{ inputs.git-sha }}-${{ inputs.release-channel }}-${{ inputs.build-type }}
              path: ${{ inputs.working-directory }}/pkg
              if-no-files-found: error
              # We can reproduce a build easily. We don't have to keep artifacts for a long time.
              retention-days: 1
