name: Prepare npm for Integration Test CI job
description: This action prepare the integration test dir for CI job

runs:
    using: composite
    steps:
        - name: Set Node.js version
          uses: actions/setup-node@v4
          with:
              node-version: 21
              cache: "npm"
              cache-dependency-path: integration_tests/package-lock.json
        - name: Enable corepack
          run: corepack enable
          shell: bash
        - run: make setup_integration_tests -j
          shell: bash
