name: Prepare Node.js package manager for Integration Test CI job
description: This action prepare the integration test dir for CI job

runs:
    using: composite
    steps:
        - name: Set Node.js version
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
          with:
              node-version: 23

        - name: Enable corepack
          run: corepack enable
          shell: bash

        - name: Get package manager's cache directory
          id: npm-cache-dir
          shell: bash
          run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
          # This step should run with pkg manager specied by corepack.
          working-directory: ./integration_tests

        - name: Get cache unique key
          id: npm-cache-key
          shell: bash
          run: echo "id=${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

        - name: Restore dependency caches
          uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
              # CAUTION: Match this on the later step.
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              # We use an exact match to avoid to store unnecessary dependencies in the later step.
              # CAUTION: Match the key name on the later step.
              key: rev1-node-pnpm-${{ runner.os }}-${{ steps.npm-cache-key.outputs.id }}

        - run: make setup_integration_tests -j
          shell: bash

        - name: Save dependency caches
          uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
          # We run this step only on _trunk_ to aim to improve a cache hit.
          # For example, dependabot's pull requests sometimes shoot down a cache hit ratio
          # by changing a lock file with multiple variants.
          # Then we cannot reuse cache ideally because the lockfile is changed high frequently under such situation.
          # Cache utilization is down.
          # So we give up to save the cache on each of pull requests.
          if: ${{ (steps.npm-cache.outputs.cache-hit != 'true') && (github.ref == 'refs/heads/main') }}
          with:
              # CAUTION: Match this on the above step.
              path: ${{ steps.npm-cache-dir.outputs.dir }}
              # CAUTION: Match the key name on the above step.
              key: rev1-node-pnpm-${{ runner.os }}-${{ steps.npm-cache-key.outputs.id }}
