packages:
  - pkgs/*

catalog:
  '@eslint/js': ^10.0.1
  '@tsconfig/strictest': ^2.0.8
  '@types/node': ^25.5.0
  ava: ^7.0.0
  eslint: ^10.1.0
  eslint-config-prettier: ^10.1.8
  globals: ^17.4.0
  option-t: ^56.1.0
  prettier: ^3.8.3
  typescript: ^6.0.3
  undici: ^7.24.6

minimumReleaseAge: 8400 # 60min * 24 * 7. This should be matched with dependabot's cooldown setting.

trustPolicy: no-downgrade
