packages:
    - pkgs/*

catalog:
    '@eslint/js': ^9.33.0
    '@tsconfig/strictest': ^2.0.5
    '@types/node': ^24.3.1
    ava: ^6.4.1
    eslint: ^9.35.0
    eslint-config-prettier: ^10.1.8
    globals: ^16.3.0
    option-t: ^54.2.3
    prettier: ^3.6.2
    typescript: ^5.9.2
    undici: ^7.15.0
