packages:
  - pkgs/*

catalog:
  '@eslint/js': ^9.35.0
  '@tsconfig/strictest': ^2.0.6
  '@types/node': ^24.5.2
  ava: ^6.4.1
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  globals: ^16.3.0
  option-t: ^55.1.0
  prettier: ^3.6.2
  typescript: ^5.9.2
  undici: ^7.15.0
