packages:
  - pkgs/*

catalog:
  '@eslint/js': ^9.39.1
  '@tsconfig/strictest': ^2.0.8
  '@types/node': ^25.0.3
  ava: ^6.4.1
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  globals: ^16.5.0
  option-t: ^55.1.0
  prettier: ^3.7.3
  typescript: ^5.9.3
  undici: ^7.16.0
