[package]
name = "c_at_e_main"
publish.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
fastly = "^0.8.7"

[features]
default = [
    # We want to be able to rollout this application to production at all time.
    # Thus we use _production_ as our default build feature set.
    "production"
]

# These feature flags represents _release channel_.
# These are mutually exclusive. You cannot enable both of them.
production = []
canary = []
