[package]
name = "c_at_e_main"
publish = false
version = "0.0.0"
edition = "2021"
rust-version = "1.64"

[dependencies]
fastly = "^0.8.7"

[features]
default = [
    # We want to be able to rollout this application to production at all time.
    # Thus we use _production_ as our default build feature set.
    "production"
]

# These feature flags represents _release channel_.
# These are mutually exclusive. You cannot enable both of them.
production = []
canary = []
