name: Prepare CI to compile
description: This action prepare CI to compile and cache cachable items

runs:
    using: composite
    steps:
        - name: Install Rust toolchain
          uses: ./.github/actions/rust_toolchain
          with:
              toolchain: "1.72"
              profile: default
              target: wasm32-wasi
              override: true
              cache: true

        - uses: actions/cache@v3
          with:
              # We can cache ./target/ directory to cache a build intermediate artifacts
              # but then we must add rust toolchain's hash to the cache key.
              # And also, we need to think to add the key to indicate a build profile
              path: |
                  ~/.cargo/
                  !~/.cargo/bin
                  !~/.cargo/env
              key: rev1-cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.lock') }}

        - name: Fetch dependency packages
          shell: bash
          run: cargo fetch --locked
