name: Download a build artifact
description: This action provides a uniform way to download a build artifact.

inputs:
    git-sha:
        required: true
    release-channel:
        required: true
    build-type:
        required: true
    working-directory:
        default: ${{ github.workspace }}
        required: false

runs:
    using: composite
    steps:
        - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
          with:
              name: application-${{ inputs.git-sha }}-${{ inputs.release-channel }}-${{ inputs.build-type }}
              path: ${{ inputs.working-directory }}/pkg
